# Generated by Django 5.0.4 on 2024-04-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя сотрудника')),
                ('position', models.CharField(max_length=255, verbose_name='Должность сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('due_to', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Статус выполнения задачи')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.employee', verbose_name='Выполняющий задачу сотрудник')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.task', verbose_name='Родительская задача')),
            ],
        ),
    ]
